DOMAIN = "connecthome"

from homeassistant.const import Platform

PLATFORMS = [
    Platform.SENSOR,
    Platform.BINARY_SENSOR,
    Platform.SWITCH,
    Platform.LIGHT,
    Platform.COVER,
    Platform.CLIMATE,
    Platform.LOCK,
]

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_VERIFY_SSL = "verify_ssl"

DEFAULT_PORT = 80
DISCOVERY_PORT = 17318
DISCOVERY_MESSAGE = "CONNECTHOME_BUTLER_DETECT"
DISCOVERY_TIMEOUT = 3

DEVICE_TYPE_SWITCH = "DevSwitch"
DEVICE_TYPE_DIMMER = "DevDimmer"
DEVICE_TYPE_DIMMER_COLOR = "DevDimmerColor"
DEVICE_TYPE_SHUTTER = "DevShutter"
DEVICE_TYPE_BINARY_SENSOR = "DevBinarySensor"
DEVICE_TYPE_TEMPERATURE = "DevTemperature"
DEVICE_TYPE_HYGROMETRY = "DevHygrometry"
DEVICE_TYPE_LUMINOSITY = "DevLuminosity"
DEVICE_TYPE_GENERIC_SENSOR = "DevGenericSensor"
DEVICE_TYPE_THERMOSTAT = "DevThermostat"
DEVICE_TYPE_DOOR_LOCK = "DevDoorLock"
DEVICE_TYPE_METER = "DevMeter"
DEVICE_TYPE_GATEWAY = "DevGateway"
DEVICE_TYPE_UNKNOWN = "DevUnknown"

IFACE_SWITCH_BINARY = "SwitchBinary"
IFACE_SWITCH_MULTILEVEL = "SwitchMultilevel"
IFACE_SWITCH_COLOR = "SwitchColor"
IFACE_SHUTTER = "Shutter"
IFACE_SENSOR_BINARY = "SensorBinary"
IFACE_SENSOR_MULTILEVEL = "SensorMultilevel"
IFACE_THERMOSTAT_MODE = "ThermostatMode"
IFACE_THERMOSTAT_SETPOINT = "ThermostatSetpoint"
IFACE_THERMOSTAT_OPERATING_STATE = "ThermostatOperatingState"
IFACE_MULTICHANNEL_ROOT = "MultichannelRoot"
IFACE_MULTICHANNEL_ENDPOINT = "MultichannelEndpoint"
IFACE_PARENT_DEVICE = "ParentDevice"
IFACE_CHILD_DEVICE = "ChildDevice"

PARAM_STATUS = "Status"
PARAM_LEVEL = "Level"
PARAM_VALUE = "Value"
PARAM_TRIPPED = "Tripped"
PARAM_ARMED = "Armed"
PARAM_SENSOR_TYPE = "sensorType"
PARAM_VALUE_SCALE = "valueScale"
PARAM_VALUE_UNIT = "valueUnit"
PARAM_CURRENT_MODE = "currentMode"
PARAM_AVAILABLE_MODES = "availableModes"
PARAM_CURRENT_SETPOINTS = "currentSetpoints"
PARAM_CURRENT_STATE = "currentState"
PARAM_SUPPORTED_COMPONENTS = "supportedComponents"
PARAM_CURRENT_COMPONENT_VALUES = "currentComponentValues"
PARAM_STOPABLE = "stopable"

POLL_EVENT_DEVICE_CHANGED = "DeviceChanged"
POLL_EVENT_DEVICE_LIST_CHANGED = "DeviceListChanged"
POLL_EVENT_ACTION_STATUS_REPORT = "ActionStatusReport"

SENSOR_TYPE_TEMPERATURE = "AirTemperature"
SENSOR_TYPE_TEMPERATURE_ALT = "Temperature"
SENSOR_TYPE_HUMIDITY = "Humidity"
SENSOR_TYPE_LUMINOSITY = "Luminosity"
SENSOR_TYPE_POWER = "Power"

TEMPERATURE_SENSOR_TYPES = {SENSOR_TYPE_TEMPERATURE, SENSOR_TYPE_TEMPERATURE_ALT}
HUMIDITY_SENSOR_TYPES = {SENSOR_TYPE_HUMIDITY}
LUMINOSITY_SENSOR_TYPES = {SENSOR_TYPE_LUMINOSITY}
POWER_SENSOR_TYPES = {SENSOR_TYPE_POWER}
